package(default_visibility = ["//visibility:public"])

java_test(
    name = "linkedlist",
    srcs = ["LinkedList_T.java"],
    test_class = "edu.berkeley.cs.util.LinkedList_T",
    deps = [
        "//java/src/edu/berkeley/cs/util",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "splaylist",
    srcs = ["SplayList_T.java"],
    test_class = "edu.berkeley.cs.util.SplayList_T",
    deps = [
        "//java/src/edu/berkeley/cs/util",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "queue",
    srcs = ["Queue_T.java"],
    test_class = "edu.berkeley.cs.util.Queue_T",
    deps = [
        "//java/src/edu/berkeley/cs/util",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "stack",
    srcs = ["Stack_T.java"],
    test_class = "edu.berkeley.cs.util.Stack_T",
    deps = [
        "//java/src/edu/berkeley/cs/util",
        "//thirdparty:junit4",
    ],
)
