package(default_visibility = ["//visibility:public"])

py_test(
    name = "elementary",
    srcs = ["elementary.py"],
    deps = [
        "//python/src/sort",
        "//python/test/util:utilities",
    ],
)

py_test(
    name = "merge",
    srcs = ["merge.py"],
    deps = [
        "//python/src/sort",
        "//python/src/util",
        "//python/test/util:utilities",
    ],
)

py_test(
    name = "quick",
    srcs = ["quick.py"],
    deps = [
        "//python/src/sort",
        "//python/test/util:utilities",
    ],
)
