package(default_visibility = ["//visibility:public"])

java_test(
    name = "calculator",
    srcs = ["Calculator_T.java"],
    test_class = "edu.berkeley.cs.app.Calculator_T",
    deps = [
        "//java/src/edu/berkeley/cs/app",
        "//thirdparty:junit4",
    ],
)
