package(default_visibility = ["//visibility:public"])

py_library(
    name = "utilities",
    srcs = ["utilities.py"],
)

py_test(
    name = "linkedlist",
    srcs = ["linkedlist.py"],
    deps = ["//python/src/util"],
)

py_test(
    name = "splaylist",
    srcs = ["splaylist.py"],
    deps = ["//python/src/util"],
)

py_test(
    name = "queue",
    srcs = ["queue.py"],
    deps = ["//python/src/util"],
)

py_test(
    name = "stack",
    srcs = ["stack.py"],
    deps = ["//python/src/util"],
)
